//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyManager.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocietyManager.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your account has been activated..
        /// </summary>
        public static string Account_ActivationMessage {
            get {
                return ResourceManager.GetString("Account_ActivationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the account for {0}? .
        /// </summary>
        public static string Account_ConfirmDeleteFormatString {
            get {
                return ResourceManager.GetString("Account_ConfirmDeleteFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string Account_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Account_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Account_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string Account_Create {
            get {
                return ResourceManager.GetString("Account_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has been created and the credentials have been sent to the user..
        /// </summary>
        public static string Account_CredentialsSent {
            get {
                return ResourceManager.GetString("Account_CredentialsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already exists..
        /// </summary>
        public static string Account_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("Account_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address specified is unknown..
        /// </summary>
        public static string Account_EmailUnknown {
            get {
                return ResourceManager.GetString("Account_EmailUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Username.
        /// </summary>
        public static string Account_ForgotUsername {
            get {
                return ResourceManager.GetString("Account_ForgotUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to you with your username. .
        /// </summary>
        public static string Account_ForgotUsernameEmailSent {
            get {
                return ResourceManager.GetString("Account_ForgotUsernameEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string Account_InvalidPassword {
            get {
                return ResourceManager.GetString("Account_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string Account_InvalidUsername {
            get {
                return ResourceManager.GetString("Account_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Account_LoginFailure {
            get {
                return ResourceManager.GetString("Account_LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via your {0} account.
        /// </summary>
        public static string Account_LoginSiteNameFormatString {
            get {
                return ResourceManager.GetString("Account_LoginSiteNameFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string Account_MyAccount {
            get {
                return ResourceManager.GetString("Account_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Account_NewPassword {
            get {
                return ResourceManager.GetString("Account_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed successfully..
        /// </summary>
        public static string Account_PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("Account_PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters long..
        /// </summary>
        public static string Account_PasswordMinLength {
            get {
                return ResourceManager.GetString("Account_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string Account_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Account_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is pending activation. An email has been sent to you..
        /// </summary>
        public static string Account_Pending {
            get {
                return ResourceManager.GetString("Account_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Profile.
        /// </summary>
        public static string Account_PublicProfile {
            get {
                return ResourceManager.GetString("Account_PublicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Account_Register {
            get {
                return ResourceManager.GetString("Account_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Account_RememberMe {
            get {
                return ResourceManager.GetString("Account_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Account_ResetPassword {
            get {
                return ResourceManager.GetString("Account_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. An email was sent to you..
        /// </summary>
        public static string Account_ResetPasswordEmailSent {
            get {
                return ResourceManager.GetString("Account_ResetPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Account_Role {
            get {
                return ResourceManager.GetString("Account_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was saved successfully..
        /// </summary>
        public static string Account_SavedSuccessfully {
            get {
                return ResourceManager.GetString("Account_SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Account_SignIn {
            get {
                return ResourceManager.GetString("Account_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Account_SignOut {
            get {
                return ResourceManager.GetString("Account_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string Account_UserAlreadyExists {
            get {
                return ResourceManager.GetString("Account_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application cache has been cleared..
        /// </summary>
        public static string Admin_CacheFlushedMessage {
            get {
                return ResourceManager.GetString("Admin_CacheFlushedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Management.
        /// </summary>
        public static string Admin_ContentManagement {
            get {
                return ResourceManager.GetString("Admin_ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Log.
        /// </summary>
        public static string Admin_ErrorLog {
            get {
                return ResourceManager.GetString("Admin_ErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Administration.
        /// </summary>
        public static string Admin_SiteAdministration {
            get {
                return ResourceManager.GetString("Admin_SiteAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Management.
        /// </summary>
        public static string Admin_SiteManagement {
            get {
                return ResourceManager.GetString("Admin_SiteManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Blog.
        /// </summary>
        public static string Blog_Export {
            get {
                return ResourceManager.GetString("Blog_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Blog.
        /// </summary>
        public static string Blog_Import {
            get {
                return ResourceManager.GetString("Blog_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the category titled &quot;{0}&quot;?.
        /// </summary>
        public static string Category_ConfirmDeleteFormatString {
            get {
                return ResourceManager.GetString("Category_ConfirmDeleteFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        public static string Category_Create {
            get {
                return ResourceManager.GetString("Category_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Category_Description {
            get {
                return ResourceManager.GetString("Category_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string Category_Edit {
            get {
                return ResourceManager.GetString("Category_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        public static string Comment_ConfirmDeleteString {
            get {
                return ResourceManager.GetString("Comment_ConfirmDeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag comment.
        /// </summary>
        public static string Comment_Flag {
            get {
                return ResourceManager.GetString("Comment_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administrator has been notified..
        /// </summary>
        public static string Comment_FlaggedMessage {
            get {
                return ResourceManager.GetString("Comment_FlaggedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate Comments.
        /// </summary>
        public static string Comment_Moderate {
            get {
                return ResourceManager.GetString("Comment_Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment has been submitted and is awaiting moderation..
        /// </summary>
        public static string Comment_PendingModeration {
            get {
                return ResourceManager.GetString("Comment_PendingModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment has been submitted. Thanks for your feedback!.
        /// </summary>
        public static string Comment_Submitted {
            get {
                return ResourceManager.GetString("Comment_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, comments are disabled..
        /// </summary>
        public static string Comments_AreDisabled {
            get {
                return ResourceManager.GetString("Comments_AreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string CommentStatus_Any {
            get {
                return ResourceManager.GetString("CommentStatus_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string CommentStatus_Approved {
            get {
                return ResourceManager.GetString("CommentStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string CommentStatus_Pending {
            get {
                return ResourceManager.GetString("CommentStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. The message was sent..
        /// </summary>
        public static string Contact_EmailSentSucessfully {
            get {
                return ResourceManager.GetString("Contact_EmailSentSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the page titled &quot;{0}&quot;?.
        /// </summary>
        public static string Page_ConfirmDeleteFormatString {
            get {
                return ResourceManager.GetString("Page_ConfirmDeleteFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Page.
        /// </summary>
        public static string Page_Create {
            get {
                return ResourceManager.GetString("Page_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page.
        /// </summary>
        public static string Page_Edit {
            get {
                return ResourceManager.GetString("Page_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page was saved successfully..
        /// </summary>
        public static string Page_SavedSuccessfully {
            get {
                return ResourceManager.GetString("Page_SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are comments enabled.
        /// </summary>
        public static string Post_AreCommentsEnabled {
            get {
                return ResourceManager.GetString("Post_AreCommentsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Post_Author {
            get {
                return ResourceManager.GetString("Post_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Post_Categories {
            get {
                return ResourceManager.GetString("Post_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the post titled &quot;{0}&quot;?.
        /// </summary>
        public static string Post_ConfirmDeleteFormatString {
            get {
                return ResourceManager.GetString("Post_ConfirmDeleteFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Post.
        /// </summary>
        public static string Post_CreateTitle {
            get {
                return ResourceManager.GetString("Post_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Post_Description {
            get {
                return ResourceManager.GetString("Post_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        public static string Post_Edit {
            get {
                return ResourceManager.GetString("Post_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        public static string Post_EditTitle {
            get {
                return ResourceManager.GetString("Post_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract from title.
        /// </summary>
        public static string Post_ExtractSlugLinkText {
            get {
                return ResourceManager.GetString("Post_ExtractSlugLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Post_Featured {
            get {
                return ResourceManager.GetString("Post_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag post.
        /// </summary>
        public static string Post_Flag {
            get {
                return ResourceManager.GetString("Post_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post has been flagged and the administrator has been notified..
        /// </summary>
        public static string Post_Flagged_Message {
            get {
                return ResourceManager.GetString("Post_Flagged_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string Post_LastModified {
            get {
                return ResourceManager.GetString("Post_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the first to rate this post..
        /// </summary>
        public static string Post_NotRatedYet {
            get {
                return ResourceManager.GetString("Post_NotRatedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string Post_PublishDate {
            get {
                return ResourceManager.GetString("Post_PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Post_Published {
            get {
                return ResourceManager.GetString("Post_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post was saved successfully..
        /// </summary>
        public static string Post_SavedSuccessfully {
            get {
                return ResourceManager.GetString("Post_SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        public static string Post_Slug {
            get {
                return ResourceManager.GetString("Post_Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to cast vote..
        /// </summary>
        public static string Post_StarRatingClickToVote {
            get {
                return ResourceManager.GetString("Post_StarRatingClickToVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must login to vote..
        /// </summary>
        public static string Post_StarRatingLoginToVote {
            get {
                return ResourceManager.GetString("Post_StarRatingLoginToVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently rated {0:f2} by {1} people.
        /// </summary>
        public static string Post_StarRatingText {
            get {
                return ResourceManager.GetString("Post_StarRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Post_Upload {
            get {
                return ResourceManager.GetString("Post_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image or file.
        /// </summary>
        public static string Post_UploadLinkText {
            get {
                return ResourceManager.GetString("Post_UploadLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Raw HTML Editor.
        /// </summary>
        public static string Post_UseRawHTMLEditor {
            get {
                return ResourceManager.GetString("Post_UseRawHTMLEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Property.
        /// </summary>
        public static string Property_CreateTitle {
            get {
                return ResourceManager.GetString("Property_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the property titled &quot;{0}&quot;?.
        /// </summary>
        public static string Property_Delete {
            get {
                return ResourceManager.GetString("Property_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results For.
        /// </summary>
        public static string Search_ResultsFor {
            get {
                return ResourceManager.GetString("Search_ResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Email Address.
        /// </summary>
        public static string Settings_AdminEmailAddress {
            get {
                return ResourceManager.GetString("Settings_AdminEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Anonymous Comments.
        /// </summary>
        public static string Settings_AllowAnonymousComments {
            get {
                return ResourceManager.GetString("Settings_AllowAnonymousComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Anonymous Ratings.
        /// </summary>
        public static string Settings_AllowAnonymousRatings {
            get {
                return ResourceManager.GetString("Settings_AllowAnonymousRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Open Registration.
        /// </summary>
        public static string Settings_AllowOpenRegistration {
            get {
                return ResourceManager.GetString("Settings_AllowOpenRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are Comments Enabled.
        /// </summary>
        public static string Settings_AreCommentsEnabled {
            get {
                return ResourceManager.GetString("Settings_AreCommentsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import and export data using the BlogML format..
        /// </summary>
        public static string Settings_BlogMLDescription {
            get {
                return ResourceManager.GetString("Settings_BlogMLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Email Subject Prefix.
        /// </summary>
        public static string Settings_CommentEmailSubjectPrefix {
            get {
                return ResourceManager.GetString("Settings_CommentEmailSubjectPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        public static string Settings_DateFormat {
            get {
                return ResourceManager.GetString("Settings_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Description.
        /// </summary>
        public static string Settings_Description {
            get {
                return ResourceManager.GetString("Settings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Settings_Email {
            get {
                return ResourceManager.GetString("Settings_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SMTP Authentication.
        /// </summary>
        public static string Settings_EnableSmtpAuthentication {
            get {
                return ResourceManager.GetString("Settings_EnableSmtpAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Format.
        /// </summary>
        public static string Settings_FeedFormat {
            get {
                return ResourceManager.GetString("Settings_FeedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Headers.
        /// </summary>
        public static string Settings_HostHeaderValues {
            get {
                return ResourceManager.GetString("Settings_HostHeaderValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the host header names (one per line) that will be used for this site..
        /// </summary>
        public static string Settings_HostHeaderValuesDescription {
            get {
                return ResourceManager.GetString("Settings_HostHeaderValuesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlogML.
        /// </summary>
        public static string Settings_Import {
            get {
                return ResourceManager.GetString("Settings_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Meta Description.
        /// </summary>
        public static string Settings_MetaDescription {
            get {
                return ResourceManager.GetString("Settings_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Meta Keywords.
        /// </summary>
        public static string Settings_MetaKeywords {
            get {
                return ResourceManager.GetString("Settings_MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate Comments.
        /// </summary>
        public static string Settings_ModerateComments {
            get {
                return ResourceManager.GetString("Settings_ModerateComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string Settings_Name {
            get {
                return ResourceManager.GetString("Settings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Settings_Posts {
            get {
                return ResourceManager.GetString("Settings_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts Per Page.
        /// </summary>
        public static string Settings_PostsPerPage {
            get {
                return ResourceManager.GetString("Settings_PostsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Theme.
        /// </summary>
        public static string Settings_PreviewTheme {
            get {
                return ResourceManager.GetString("Settings_PreviewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings were saved successfully..
        /// </summary>
        public static string Settings_SavedSuccessfully {
            get {
                return ResourceManager.GetString("Settings_SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Comment Email.
        /// </summary>
        public static string Settings_SendCommentEmail {
            get {
                return ResourceManager.GetString("Settings_SendCommentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SSL.
        /// </summary>
        public static string Settings_SmtpEnableSsl {
            get {
                return ResourceManager.GetString("Settings_SmtpEnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Password.
        /// </summary>
        public static string Settings_SmtpPassword {
            get {
                return ResourceManager.GetString("Settings_SmtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Port.
        /// </summary>
        public static string Settings_SmtpPort {
            get {
                return ResourceManager.GetString("Settings_SmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server.
        /// </summary>
        public static string Settings_SmtpServer {
            get {
                return ResourceManager.GetString("Settings_SmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Username.
        /// </summary>
        public static string Settings_SmtpUsername {
            get {
                return ResourceManager.GetString("Settings_SmtpUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Networking Support.
        /// </summary>
        public static string Settings_SocialNetworkingSupport {
            get {
                return ResourceManager.GetString("Settings_SocialNetworkingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Script.
        /// </summary>
        public static string Settings_TrackingScript {
            get {
                return ResourceManager.GetString("Settings_TrackingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JavaScript code from i.e. Google Analytics. Will be added in the bottom of each page regardless of the theme. (remember to add the &amp;lt;script&amp;gt; tags)..
        /// </summary>
        public static string Settings_TrackingScriptDescription {
            get {
                return ResourceManager.GetString("Settings_TrackingScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Post Visits.
        /// </summary>
        public static string Settings_TrackPostVisits {
            get {
                return ResourceManager.GetString("Settings_TrackPostVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address of administrative account.
        /// </summary>
        public static string Setup_AdminEmailLabel {
            get {
                return ResourceManager.GetString("Setup_AdminEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the password.
        /// </summary>
        public static string Setup_ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("Setup_ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        public static string Setup_ConnectionStringLabel {
            get {
                return ResourceManager.GetString("Setup_ConnectionStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to store your data?.
        /// </summary>
        public static string Setup_DataStorageLabel {
            get {
                return ResourceManager.GetString("Setup_DataStorageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer a few questions to configure your site..
        /// </summary>
        public static string Setup_Directions {
            get {
                return ResourceManager.GetString("Setup_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Setup.
        /// </summary>
        public static string Setup_FinishText {
            get {
                return ResourceManager.GetString("Setup_FinishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Setup_GetStarted {
            get {
                return ResourceManager.GetString("Setup_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a password.
        /// </summary>
        public static string Setup_PasswordLabel {
            get {
                return ResourceManager.GetString("Setup_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of website.
        /// </summary>
        public static string Setup_WebsiteDescriptionLabel {
            get {
                return ResourceManager.GetString("Setup_WebsiteDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of your website?.
        /// </summary>
        public static string Setup_WebsiteNameLabel {
            get {
                return ResourceManager.GetString("Setup_WebsiteNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the url of your website?.
        /// </summary>
        public static string Setup_WebsiteUrlLabel {
            get {
                return ResourceManager.GetString("Setup_WebsiteUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Society Manager.
        /// </summary>
        public static string Setup_Welcome {
            get {
                return ResourceManager.GetString("Setup_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use built-in data storage (SQL Server Compact).
        /// </summary>
        public static string StorageOption_SqlCompact {
            get {
                return ResourceManager.GetString("StorageOption_SqlCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an existing SQL Server (or SQL Express) database.
        /// </summary>
        public static string StorageOption_SqlServer {
            get {
                return ResourceManager.GetString("StorageOption_SqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tag.
        /// </summary>
        public static string Tag_Create {
            get {
                return ResourceManager.GetString("Tag_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL specified. .
        /// </summary>
        public static string Validation_InvalidUrl {
            get {
                return ResourceManager.GetString("Validation_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified name is already in use. .
        /// </summary>
        public static string Validation_NameAlreadyInUse {
            get {
                return ResourceManager.GetString("Validation_NameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied..
        /// </summary>
        public static string Validation_PermissionDenied {
            get {
                return ResourceManager.GetString("Validation_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and try again..
        /// </summary>
        public static string Validation_PleaseCorrectErrors {
            get {
                return ResourceManager.GetString("Validation_PleaseCorrectErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you already voted..
        /// </summary>
        public static string Vote_AlreadyVoted {
            get {
                return ResourceManager.GetString("Vote_AlreadyVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote was cast successfully..
        /// </summary>
        public static string Vote_Casted {
            get {
                return ResourceManager.GetString("Vote_Casted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you must be logged in to vote..
        /// </summary>
        public static string Vote_MustBeLoggedIn {
            get {
                return ResourceManager.GetString("Vote_MustBeLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you&apos;ve just configured your website. You can add more posts, pages and more by using the site administration link above..
        /// </summary>
        public static string Welcome_Post {
            get {
                return ResourceManager.GetString("Welcome_Post", resourceCulture);
            }
        }
    }
}
